#!/bin/bash

# Gerar string aleatória para uso no nome do arquivo de backup
random=$(cat /dev/urandom | tr -dc '[:alnum:]' | head -c 5)

# Obter data e hora atual para uso no nome do arquivo de backup
dato=$(date "+%d-%m-%Y_%Hh-%Mm-%Ss")

# Caminho absoluto para o diretório de backup
backup_dir="/root/backupAuto"

# Criar diretório de backup se não existir
mkdir -p "$backup_dir" && echo "Directorio de copia de seguridad creado con éxito"

# Adicionar tarefa cron se ainda não estiver configurada
if ! crontab -l | grep -q "0 */5 * * * backmod"; then
    (crontab -l 2>/dev/null; echo "0 */5 * * * backmod") | crontab - && echo "Tarea cron agregada con éxito"
fi

# Copiar arquivos para o diretório de backup
if cp /root/DTunnel/prisma/database.db /root/DTunnel/.env /root/DTunnel/painelbackup; then
    echo "Archivos copiados con éxito"
else
    echo "Error al copiar archivos"
    exit 1
fi

# Compactar o diretório de backup
if zip -r "/root/backupAuto/painelbackup-$dato-$random.zip" /root/DTunnel/painelbackup; then
    echo "Copia de seguridad comprimida con éxito"
else
    echo "Error al comprimir copia de seguridad"
    exit 1
fi

# Remover o diretório de backup temporário
rm -rf /root/DTunnel/painelbackup && echo "Directorio temporal eliminado con éxito"
