#!/bin/bash

do_backup() {
  clear
  echo "Copia de seguridad..."
  cd /root/DTunnel
  #rm -r painelbackup > /dev/null
  #mkdir painelbackup > /dev/null
  cp prisma/database.db painelbackup
  cp .env painelbackup
  zip -r painelbackup.zip painelbackup
  mv painelbackup.zip /root
  echo
  echo "panelbackup.zip guardado en /root"
  echo
  exit 0
}

toggle_auto_backup() {
  clear
  read -p "DESEA HABILITAR LA COPIA DE SEGURIDAD AUTOMÁTICA? (s/n) " atb
  [[ $atb = @(s|S) ]] && {
    echo "Ativando...."
    backmod
    echo
    echo "Copia de seguridad activa de 5 en 5 horas!"
    exit 0
  }
  menudt
}

remove_panel() {
  clear
  read -p "DESEA ELIMINAR EL PANEL? (s/n) " rev
  [[ $rev = @(s|S) ]] && {
    echo "Eliminación..."
    poff
    rm /bin/pon /bin/poff /bin/menudt /bin/backmod
    rm -r /root/DTunnel
    echo "Eliminado con éxito!"
    exit 0
  }
  menudt
}

restore_backup() {
  clear
  [[ ! -e /root/painelbackup.zip ]] && {
    echo "Archivo panelbackup.zip no encontrado en /root"
    sleep 4
    menudt
  }
  read -p "DESEA RESTAURAR LA COPIA DE SEGURIDAD? (s/n) " rapi
  [[ $rapi = @(s|S) ]] && {
    echo "Restaurando..."
    cd /root/DTunnel
    rm prisma/database.db
    rm .env
    cd /root
    unzip painelbackup.zip
    cd painelbackup
    mv database.db ../DTunnel/prisma
    mv .env ../DTunnel
    cd /root
    rm -r painelbackup
    pon
    echo
    echo "Copia de seguridad restaurada con éxito!"
    exit 0
  }
  [[ $rapi = @(n|N) ]] && {
    echo "Volviendo a menudt"
    sleep 2
    menudt
  }
  menudt
}
#[[ ! -e /root/DTunnel/src/index.ts ]] && exit 0
menudt() {
  clear
echo -e "\033[1;34m╔══════════════════════════╗\033[0m" 
echo -e "\033[1;34m║\033[1;41m\033[1;32m MENÚ PANEL DTUNNEL-MOD   \033[0m\033[1;34m║" 
echo -e "\033[1;34m╠══════════════════════════╣\033[0m" 
echo -e "\033[1;34m║\033[1;36m[\033[1;32m01\033[1;36m] \033[1;32m• \033[1;31mCOPIA DE SEGURIDAD \033[1;34m║" 
echo -e "\033[1;34m║\033[1;36m[\033[1;32m02\033[1;36m] \033[1;32m• \033[1;31mRESTAURAR COPIA    \033[1;34m║" 
echo -e "\033[1;34m║\033[1;36m[\033[1;32m03\033[1;36m] \033[1;32m• \033[1;31mREINICIAR PANEL    \033[1;34m║" 
echo -e "\033[1;34m║\033[1;36m[\033[1;32m04\033[1;36m] \033[1;32m• \033[1;31mCOPIA AUTOMÁTICA   \033[1;34m║" 
echo -e "\033[1;34m║\033[1;36m[\033[1;32m05\033[1;36m] \033[1;32m• \033[1;31mELIMINAR PANEL     \033[1;34m║" 
echo -e "\033[1;34m║\033[1;36m[\033[1;32m00\033[1;36m] \033[1;32m• \033[1;31mSALIR              \033[1;34m║" 
echo -e "\033[1;34m╠══════════════════════════╝\033[0m" 
echo -ne "\033[1;34m╚➤ \033[1;31mINTRODUZCA UNA OPCIÓN \033[1;33m : ";
  read resp
  case $resp in
    1) 
    do_backup 
    sleep 3
    menudt
    ;;
    2) 
    restore_backup 
    sleep 3
    menudt
    ;;
    3) 
    clear
    echo "Reiniciando..."
    pon
    echo "Reiniciado correctamente!"
    sleep 3
    menudt
    ;;
    4) 
    toggle_auto_backup 
    sleep 3
    menudt
    ;;
    5) 
    remove_panel 
    ;;
    0) 
    echo "Saliendo..."
    exit 0 
    ;;
    *) 
    echo "Opción no válida!"
    sleep 3
    clear
    menudt
  esac
}
menudt
